## Librerías

In [49]:
import os
import io
import numpy as np
import pandas as pd
import seaborn as sns
from PIL import Image
from tqdm import tqdm
from random import randint
from datetime import datetime
import matplotlib.pyplot as plt
from contextlib import redirect_stdout
from matplotlib.backends.backend_pdf import PdfPages

# Modelo
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from tensorflow.keras.models import clone_model
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import keras
from keras import Input
from keras.regularizers import l2
from keras.optimizers import Adam
from keras.models import Sequential
from keras.callbacks import EarlyStopping
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

## 1. Configuración

In [2]:
BATCH_SIZE =    8
IMG_SIZE =      128
DROPOUT =       0.3
LEARNING_RATE = 0.0008
FactorLR =      0.7
EPOCHS =        40
PatienceES =    15
F_ACT =         'relu'
F_ACT_2 =       'sigmoid'

nombre_modelo = "CNN_kFold"
data_path = './data'

## 2. Cargar dataset

In [3]:
# Funcion para cargar imagenes y etiquetas
def cargar_imagenes_y_labels(data_path, clases):
    X = []
    y = []
    for idx, clase in enumerate(clases):
        clase_path = os.path.join(data_path, clase)
        imagenes = os.listdir(clase_path)
        for img_name in tqdm(imagenes, desc=f"Clase {clase}", unit="img"):
            img_path = os.path.join(clase_path, img_name)
            try:
                img = Image.open(img_path).convert('RGB')
                img = img.resize((IMG_SIZE, IMG_SIZE))
                img.verify()
                X.append(np.array(img))
                y.append(idx)
            except:
                os.remove(img_path)
    X = np.array(X).astype('float32') / 255.0
    # X = np.array(X).astype('float16') / 255.0
    y = np.array(y)
    return X, y

# Carga y split de datos
ruta_guardado = './npy_guardados'
os.makedirs(ruta_guardado, exist_ok=True)

ruta_X = os.path.join(ruta_guardado, f'X_{IMG_SIZE}.npy')
ruta_y = os.path.join(ruta_guardado, f'y_{IMG_SIZE}.npy')
if os.path.exists(ruta_X) and os.path.exists(ruta_y):
    print("🔄 Cargando datos desde archivos .npy...")
    X = np.load(ruta_X); print(f"✅ X cargado")
    y = np.load(ruta_y); print(f"✅ y cargado")
else:
    print("📥 Descargando data...")
    clases = ['neutral', 'sexy']
    X, y = cargar_imagenes_y_labels(data_path, clases)
    np.save(ruta_X, X); print("💾 X guardado")
    np.save(ruta_y, y); print("💾 y guardado")

🔄 Cargando datos desde archivos .npy...
✅ X cargado
✅ y cargado

## 3. Entrenamiento con Kfold

In [4]:
# Entrenamiento

rand = randint(0, 10000)
rand = 6497

# Dividir en entrenamiento(train+val)[90] y test[10]
X_trainval, X_test, y_trainval, y_test = train_test_split(X, y, test_size=0.1, random_state=rand, stratify=y)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=rand)

# Métricas por fold
fold_results = []
all_histories = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_trainval, y_trainval)):
    print(f"\n🔁 Fold {fold+1}/{5}")

    # Datos fold
    X_train, X_val = X_trainval[train_idx], X_trainval[val_idx]
    y_train, y_val = y_trainval[train_idx], y_trainval[val_idx]

    # Modelo
    model_fold = Sequential([
        Input(shape=(IMG_SIZE, IMG_SIZE, 3), name='input'),
        Conv2D(16, (3,3), activation=F_ACT, name='conv1'),
        MaxPooling2D(2,2, name='pool1'),

        Conv2D(32, (3,3), activation=F_ACT, name='conv2'),
        MaxPooling2D(2,2, name='pool2'),

        Conv2D(64, (3,3), activation=F_ACT, name='conv3'),
        MaxPooling2D(2,2, name='pool3'),

        Conv2D(128, (3,3), activation=F_ACT, name='conv4'),
        MaxPooling2D(2,2, name='pool4'),

        Flatten(name='flatten'),
        Dense(64, activation=F_ACT, name='dense1'),
        Dropout(DROPOUT, name='dropout'),
        Dense(1, activation=F_ACT_2, name='output')
    ])
    model_fold.compile(optimizer=Adam(learning_rate=LEARNING_RATE),
                       loss='binary_crossentropy',
                       metrics=['accuracy'])

    # Aumento de datos
    datagen = ImageDataGenerator(
        rotation_range=15,
        width_shift_range=0.1,
        height_shift_range=0.1,
        zoom_range=0.1,
        horizontal_flip=True
    )
    train_generator = datagen.flow(X_train, y_train, batch_size=BATCH_SIZE)

    # Callbacks
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=FactorLR,
                                  patience=2, min_lr=0.0001, verbose=1)
    early_stop = EarlyStopping(monitor='val_loss',
                                patience=PatienceES, restore_best_weights=True)

    # Entrenamiento
    history = model_fold.fit(
        train_generator,
        validation_data=(X_val, y_val),
        epochs=EPOCHS,
        callbacks=[early_stop, reduce_lr],
        verbose=1
    )

    # Guardar historial
    all_histories.append(history.history)

    # Evaluación fold
    val_loss, val_acc = model_fold.evaluate(X_val, y_val, verbose=0)
    y_val_pred = (model_fold.predict(X_val) > 0.5).astype(int)
    report = classification_report(y_val, y_val_pred, target_names=['neutral', 'sexy'], output_dict=True)
    conf_mat = confusion_matrix(y_val, y_val_pred)

    fold_results.append({
        'fold': fold+1,
        'val_loss': val_loss,
        'val_acc': val_acc,
        'precision': report['sexy']['precision'],
        'recall': report['sexy']['recall'],
        'f1': report['sexy']['f1-score'],
        'confusion_matrix': conf_mat,
        'history': history.history
    })

timestamp = datetime.now().strftime('%d-%m-%y_%H-%M-%S')
print(f"✅Entrenamiento terminado [{timestamp}]")

🔁 Fold 1/5
Epoch 1/40

c:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

1890/1890 ━━━━━━━━━━━━━━━━━━━━ 676s 347ms/step - accuracy: 0.6248 - loss: 0.6381 - val_accuracy: 0.6997 - val_loss: 0.5635 - learning_rate: 8.0000e-04
Epoch 2/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 285s 151ms/step - accuracy: 0.7527 - loss: 0.5113 - val_accuracy: 0.8151 - val_loss: 0.3927 - learning_rate: 8.0000e-04
Epoch 3/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 321s 169ms/step - accuracy: 0.8057 - loss: 0.4199 - val_accuracy: 0.8426 - val_loss: 0.3401 - learning_rate: 8.0000e-04
Epoch 4/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 282s 148ms/step - accuracy: 0.8278 - loss: 0.3835 - val_accuracy: 0.8526 - val_loss: 0.3337 - learning_rate: 8.0000e-04
Epoch 5/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 206s 108ms/step - accuracy: 0.8449 - loss: 0.3529 - val_accuracy: 0.8661 - val_loss: 0.3077 - learning_rate: 8.0000e-04
Epoch 6/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 199s 105ms/step - accuracy: 0.8581 - loss: 0.3366 - val_accuracy: 0.8799 - val_loss: 0.2859 - learning_rate: 8.0000e-04
Epoch 7/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 193s 102ms/step - accuracy: 0.8609 - loss: 0.3219 - val_accuracy: 0.8765 - val_loss: 0.2926 - learning_rate: 8.0000e-04
Epoch 8/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 197s 104ms/step - accuracy: 0.8651 - loss: 0.3151 - val_accuracy: 0.8786 - val_loss: 0.2835 - learning_rate: 8.0000e-04
Epoch 9/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 192s 101ms/step - accuracy: 0.8671 - loss: 0.3101 - val_accuracy: 0.8757 - val_loss: 0.3010 - learning_rate: 8.0000e-04
Epoch 10/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.8742 - loss: 0.2974
Epoch 10: ReduceLROnPlateau reducing learning rate to 0.0005599999858532101.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 203s 107ms/step - accuracy: 0.8742 - loss: 0.2974 - val_accuracy: 0.8823 - val_loss: 0.2839 - learning_rate: 8.0000e-04
Epoch 11/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 208s 109ms/step - accuracy: 0.8932 - loss: 0.2645 - val_accuracy: 0.9016 - val_loss: 0.2453 - learning_rate: 5.6000e-04
Epoch 12/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 204s 107ms/step - accuracy: 0.8981 - loss: 0.2528 - val_accuracy: 0.8775 - val_loss: 0.2795 - learning_rate: 5.6000e-04
Epoch 13/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.8944 - loss: 0.2472
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0003919999697245657.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 215s 113ms/step - accuracy: 0.8944 - loss: 0.2472 - val_accuracy: 0.8979 - val_loss: 0.2649 - learning_rate: 5.6000e-04
Epoch 14/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 220s 116ms/step - accuracy: 0.9044 - loss: 0.2345 - val_accuracy: 0.9082 - val_loss: 0.2327 - learning_rate: 3.9200e-04
Epoch 15/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 223s 117ms/step - accuracy: 0.9108 - loss: 0.2265 - val_accuracy: 0.9071 - val_loss: 0.2367 - learning_rate: 3.9200e-04
Epoch 16/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 286s 151ms/step - accuracy: 0.9052 - loss: 0.2298 - val_accuracy: 0.9167 - val_loss: 0.2176 - learning_rate: 3.9200e-04
Epoch 17/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 266s 140ms/step - accuracy: 0.9104 - loss: 0.2235 - val_accuracy: 0.8862 - val_loss: 0.2859 - learning_rate: 3.9200e-04
Epoch 18/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 251s 132ms/step - accuracy: 0.9144 - loss: 0.2153 - val_accuracy: 0.9164 - val_loss: 0.2163 - learning_rate: 3.9200e-04
Epoch 19/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 237s 125ms/step - accuracy: 0.9153 - loss: 0.2114 - val_accuracy: 0.9029 - val_loss: 0.2457 - learning_rate: 3.9200e-04
Epoch 20/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 242s 114ms/step - accuracy: 0.9186 - loss: 0.2057 - val_accuracy: 0.9204 - val_loss: 0.2055 - learning_rate: 3.9200e-04
Epoch 21/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 258s 136ms/step - accuracy: 0.9210 - loss: 0.1991 - val_accuracy: 0.9148 - val_loss: 0.2231 - learning_rate: 3.9200e-04
Epoch 22/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.9184 - loss: 0.1979
Epoch 22: ReduceLROnPlateau reducing learning rate to 0.00027439997065812347.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 268s 141ms/step - accuracy: 0.9184 - loss: 0.1979 - val_accuracy: 0.9151 - val_loss: 0.2220 - learning_rate: 3.9200e-04
Epoch 23/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 238s 125ms/step - accuracy: 0.9239 - loss: 0.1923 - val_accuracy: 0.9151 - val_loss: 0.2130 - learning_rate: 2.7440e-04
Epoch 24/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.9305 - loss: 0.1810
Epoch 24: ReduceLROnPlateau reducing learning rate to 0.00019207997538615016.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 240s 126ms/step - accuracy: 0.9305 - loss: 0.1810 - val_accuracy: 0.9143 - val_loss: 0.2145 - learning_rate: 2.7440e-04
Epoch 25/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 259s 136ms/step - accuracy: 0.9351 - loss: 0.1663 - val_accuracy: 0.9278 - val_loss: 0.1928 - learning_rate: 1.9208e-04
Epoch 26/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 232s 122ms/step - accuracy: 0.9366 - loss: 0.1651 - val_accuracy: 0.9296 - val_loss: 0.1923 - learning_rate: 1.9208e-04
Epoch 27/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 231s 122ms/step - accuracy: 0.9294 - loss: 0.1716 - val_accuracy: 0.9159 - val_loss: 0.2236 - learning_rate: 1.9208e-04
Epoch 28/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 231s 121ms/step - accuracy: 0.9348 - loss: 0.1596 - val_accuracy: 0.9307 - val_loss: 0.1915 - learning_rate: 1.9208e-04
Epoch 29/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 219s 115ms/step - accuracy: 0.9381 - loss: 0.1615 - val_accuracy: 0.9286 - val_loss: 0.1921 - learning_rate: 1.9208e-04
Epoch 30/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.9359 - loss: 0.1559
Epoch 30: ReduceLROnPlateau reducing learning rate to 0.00013445597869576886.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 269s 142ms/step - accuracy: 0.9359 - loss: 0.1559 - val_accuracy: 0.9164 - val_loss: 0.2212 - learning_rate: 1.9208e-04
Epoch 31/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 274s 144ms/step - accuracy: 0.9365 - loss: 0.1588 - val_accuracy: 0.9275 - val_loss: 0.2064 - learning_rate: 1.3446e-04
Epoch 32/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.9406 - loss: 0.1535
Epoch 32: ReduceLROnPlateau reducing learning rate to 0.0001.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 266s 140ms/step - accuracy: 0.9406 - loss: 0.1535 - val_accuracy: 0.9286 - val_loss: 0.2008 - learning_rate: 1.3446e-04
Epoch 33/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 255s 134ms/step - accuracy: 0.9421 - loss: 0.1483 - val_accuracy: 0.9315 - val_loss: 0.1891 - learning_rate: 1.0000e-04
Epoch 34/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 239s 126ms/step - accuracy: 0.9440 - loss: 0.1439 - val_accuracy: 0.9249 - val_loss: 0.2101 - learning_rate: 1.0000e-04
Epoch 35/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 242s 127ms/step - accuracy: 0.9455 - loss: 0.1418 - val_accuracy: 0.9272 - val_loss: 0.1989 - learning_rate: 1.0000e-04
Epoch 36/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 252s 133ms/step - accuracy: 0.9449 - loss: 0.1394 - val_accuracy: 0.9180 - val_loss: 0.2312 - learning_rate: 1.0000e-04
Epoch 37/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 266s 140ms/step - accuracy: 0.9453 - loss: 0.1416 - val_accuracy: 0.9238 - val_loss: 0.2166 - learning_rate: 1.0000e-04
Epoch 38/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 240s 126ms/step - accuracy: 0.9459 - loss: 0.1419 - val_accuracy: 0.9288 - val_loss: 0.2026 - learning_rate: 1.0000e-04
Epoch 39/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 230s 121ms/step - accuracy: 0.9451 - loss: 0.1439 - val_accuracy: 0.9312 - val_loss: 0.1938 - learning_rate: 1.0000e-04
Epoch 40/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 230s 121ms/step - accuracy: 0.9469 - loss: 0.1318 - val_accuracy: 0.9307 - val_loss: 0.2048 - learning_rate: 1.0000e-04
119/119 ━━━━━━━━━━━━━━━━━━━━ 9s 72ms/step

🔁 Fold 2/5
Epoch 1/40

c:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

1890/1890 ━━━━━━━━━━━━━━━━━━━━ 251s 128ms/step - accuracy: 0.6305 - loss: 0.6332 - val_accuracy: 0.7608 - val_loss: 0.4949 - learning_rate: 8.0000e-04
Epoch 2/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 305s 160ms/step - accuracy: 0.7507 - loss: 0.5152 - val_accuracy: 0.8143 - val_loss: 0.4115 - learning_rate: 8.0000e-04
Epoch 3/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 294s 155ms/step - accuracy: 0.8039 - loss: 0.4393 - val_accuracy: 0.8302 - val_loss: 0.3682 - learning_rate: 8.0000e-04
Epoch 4/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 311s 163ms/step - accuracy: 0.8233 - loss: 0.3956 - val_accuracy: 0.8587 - val_loss: 0.3262 - learning_rate: 8.0000e-04
Epoch 5/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 298s 157ms/step - accuracy: 0.8381 - loss: 0.3732 - val_accuracy: 0.8579 - val_loss: 0.3308 - learning_rate: 8.0000e-04
Epoch 6/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 241s 127ms/step - accuracy: 0.8469 - loss: 0.3580 - val_accuracy: 0.8667 - val_loss: 0.3052 - learning_rate: 8.0000e-04
Epoch 7/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 246s 129ms/step - accuracy: 0.8620 - loss: 0.3287 - val_accuracy: 0.8849 - val_loss: 0.2768 - learning_rate: 8.0000e-04
Epoch 8/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 258s 136ms/step - accuracy: 0.8642 - loss: 0.3258 - val_accuracy: 0.8817 - val_loss: 0.2794 - learning_rate: 8.0000e-04
Epoch 9/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 255s 134ms/step - accuracy: 0.8677 - loss: 0.3159 - val_accuracy: 0.8907 - val_loss: 0.2732 - learning_rate: 8.0000e-04
Epoch 10/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 258s 136ms/step - accuracy: 0.8766 - loss: 0.3016 - val_accuracy: 0.8817 - val_loss: 0.2762 - learning_rate: 8.0000e-04
Epoch 11/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.8754 - loss: 0.2938
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0005599999858532101.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 260s 137ms/step - accuracy: 0.8754 - loss: 0.2938 - val_accuracy: 0.8836 - val_loss: 0.2815 - learning_rate: 8.0000e-04
Epoch 12/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 259s 136ms/step - accuracy: 0.8906 - loss: 0.2650 - val_accuracy: 0.8894 - val_loss: 0.2617 - learning_rate: 5.6000e-04
Epoch 13/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 269s 142ms/step - accuracy: 0.8977 - loss: 0.2585 - val_accuracy: 0.9032 - val_loss: 0.2405 - learning_rate: 5.6000e-04
Epoch 14/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 270s 142ms/step - accuracy: 0.8990 - loss: 0.2488 - val_accuracy: 0.9090 - val_loss: 0.2166 - learning_rate: 5.6000e-04
Epoch 15/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 259s 136ms/step - accuracy: 0.8986 - loss: 0.2388 - val_accuracy: 0.9061 - val_loss: 0.2285 - learning_rate: 5.6000e-04
Epoch 16/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9033 - loss: 0.2387
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0003919999697245657.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 263s 138ms/step - accuracy: 0.9033 - loss: 0.2387 - val_accuracy: 0.9066 - val_loss: 0.2359 - learning_rate: 5.6000e-04
Epoch 17/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 301s 158ms/step - accuracy: 0.9127 - loss: 0.2149 - val_accuracy: 0.9164 - val_loss: 0.2158 - learning_rate: 3.9200e-04
Epoch 18/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 264s 139ms/step - accuracy: 0.9130 - loss: 0.2191 - val_accuracy: 0.9151 - val_loss: 0.2179 - learning_rate: 3.9200e-04
Epoch 19/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 257s 135ms/step - accuracy: 0.9210 - loss: 0.2084 - val_accuracy: 0.9177 - val_loss: 0.2030 - learning_rate: 3.9200e-04
Epoch 20/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 233s 122ms/step - accuracy: 0.9175 - loss: 0.2034 - val_accuracy: 0.9177 - val_loss: 0.2089 - learning_rate: 3.9200e-04
Epoch 21/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.9226 - loss: 0.2020
Epoch 21: ReduceLROnPlateau reducing learning rate to 0.00027439997065812347.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 233s 123ms/step - accuracy: 0.9226 - loss: 0.2020 - val_accuracy: 0.9185 - val_loss: 0.2093 - learning_rate: 3.9200e-04
Epoch 22/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 249s 131ms/step - accuracy: 0.9302 - loss: 0.1846 - val_accuracy: 0.9225 - val_loss: 0.2179 - learning_rate: 2.7440e-04
Epoch 23/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.9263 - loss: 0.1828
Epoch 23: ReduceLROnPlateau reducing learning rate to 0.00019207997538615016.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 259s 136ms/step - accuracy: 0.9263 - loss: 0.1828 - val_accuracy: 0.9185 - val_loss: 0.2072 - learning_rate: 2.7440e-04
Epoch 24/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 248s 130ms/step - accuracy: 0.9371 - loss: 0.1624 - val_accuracy: 0.9288 - val_loss: 0.1929 - learning_rate: 1.9208e-04
Epoch 25/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 226s 119ms/step - accuracy: 0.9356 - loss: 0.1650 - val_accuracy: 0.9241 - val_loss: 0.1981 - learning_rate: 1.9208e-04
Epoch 26/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.9336 - loss: 0.1620
Epoch 26: ReduceLROnPlateau reducing learning rate to 0.00013445597869576886.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 237s 125ms/step - accuracy: 0.9336 - loss: 0.1620 - val_accuracy: 0.9280 - val_loss: 0.1937 - learning_rate: 1.9208e-04
Epoch 27/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 234s 123ms/step - accuracy: 0.9391 - loss: 0.1507 - val_accuracy: 0.9243 - val_loss: 0.1957 - learning_rate: 1.3446e-04
Epoch 28/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 227s 119ms/step - accuracy: 0.9404 - loss: 0.1572 - val_accuracy: 0.9286 - val_loss: 0.1920 - learning_rate: 1.3446e-04
Epoch 29/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 251s 132ms/step - accuracy: 0.9419 - loss: 0.1481 - val_accuracy: 0.9272 - val_loss: 0.2010 - learning_rate: 1.3446e-04
Epoch 30/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 235s 124ms/step - accuracy: 0.9402 - loss: 0.1524 - val_accuracy: 0.9288 - val_loss: 0.1907 - learning_rate: 1.3446e-04
Epoch 31/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 262s 138ms/step - accuracy: 0.9405 - loss: 0.1554 - val_accuracy: 0.9272 - val_loss: 0.1935 - learning_rate: 1.3446e-04
Epoch 32/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 277s 145ms/step - accuracy: 0.9375 - loss: 0.1503 - val_accuracy: 0.9299 - val_loss: 0.1885 - learning_rate: 1.3446e-04
Epoch 33/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 260s 137ms/step - accuracy: 0.9468 - loss: 0.1392 - val_accuracy: 0.9328 - val_loss: 0.1804 - learning_rate: 1.3446e-04
Epoch 34/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 248s 130ms/step - accuracy: 0.9446 - loss: 0.1448 - val_accuracy: 0.9304 - val_loss: 0.1941 - learning_rate: 1.3446e-04
Epoch 35/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.9422 - loss: 0.1462
Epoch 35: ReduceLROnPlateau reducing learning rate to 0.0001.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 240s 127ms/step - accuracy: 0.9422 - loss: 0.1462 - val_accuracy: 0.9249 - val_loss: 0.1935 - learning_rate: 1.3446e-04
Epoch 36/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 233s 122ms/step - accuracy: 0.9493 - loss: 0.1339 - val_accuracy: 0.9296 - val_loss: 0.1914 - learning_rate: 1.0000e-04
Epoch 37/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 236s 124ms/step - accuracy: 0.9505 - loss: 0.1387 - val_accuracy: 0.9296 - val_loss: 0.1957 - learning_rate: 1.0000e-04
Epoch 38/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 229s 121ms/step - accuracy: 0.9508 - loss: 0.1316 - val_accuracy: 0.9315 - val_loss: 0.1944 - learning_rate: 1.0000e-04
Epoch 39/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 237s 125ms/step - accuracy: 0.9470 - loss: 0.1307 - val_accuracy: 0.9251 - val_loss: 0.2013 - learning_rate: 1.0000e-04
Epoch 40/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 221s 116ms/step - accuracy: 0.9450 - loss: 0.1335 - val_accuracy: 0.9246 - val_loss: 0.2054 - learning_rate: 1.0000e-04
119/119 ━━━━━━━━━━━━━━━━━━━━ 9s 70ms/step

🔁 Fold 3/5
Epoch 1/40

c:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

1890/1890 ━━━━━━━━━━━━━━━━━━━━ 232s 119ms/step - accuracy: 0.5846 - loss: 0.6584 - val_accuracy: 0.7656 - val_loss: 0.4902 - learning_rate: 8.0000e-04
Epoch 2/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 241s 126ms/step - accuracy: 0.7667 - loss: 0.4867 - val_accuracy: 0.8241 - val_loss: 0.3944 - learning_rate: 8.0000e-04
Epoch 3/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 214s 113ms/step - accuracy: 0.8200 - loss: 0.4074 - val_accuracy: 0.8601 - val_loss: 0.3303 - learning_rate: 8.0000e-04
Epoch 4/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 209s 110ms/step - accuracy: 0.8375 - loss: 0.3693 - val_accuracy: 0.8730 - val_loss: 0.3105 - learning_rate: 8.0000e-04
Epoch 5/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 206s 108ms/step - accuracy: 0.8582 - loss: 0.3358 - val_accuracy: 0.8714 - val_loss: 0.3024 - learning_rate: 8.0000e-04
Epoch 6/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 211s 111ms/step - accuracy: 0.8641 - loss: 0.3197 - val_accuracy: 0.8802 - val_loss: 0.2913 - learning_rate: 8.0000e-04
Epoch 7/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 256s 135ms/step - accuracy: 0.8687 - loss: 0.3109 - val_accuracy: 0.8810 - val_loss: 0.2787 - learning_rate: 8.0000e-04
Epoch 8/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 249s 131ms/step - accuracy: 0.8740 - loss: 0.2958 - val_accuracy: 0.8952 - val_loss: 0.2747 - learning_rate: 8.0000e-04
Epoch 9/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 246s 129ms/step - accuracy: 0.8836 - loss: 0.2771 - val_accuracy: 0.8976 - val_loss: 0.2491 - learning_rate: 8.0000e-04
Epoch 10/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 214s 113ms/step - accuracy: 0.8840 - loss: 0.2774 - val_accuracy: 0.8921 - val_loss: 0.2561 - learning_rate: 8.0000e-04
Epoch 11/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.8898 - loss: 0.2702
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0005599999858532101.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 226s 119ms/step - accuracy: 0.8898 - loss: 0.2702 - val_accuracy: 0.8656 - val_loss: 0.3226 - learning_rate: 8.0000e-04
Epoch 12/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 250s 132ms/step - accuracy: 0.8960 - loss: 0.2476 - val_accuracy: 0.8968 - val_loss: 0.2391 - learning_rate: 5.6000e-04
Epoch 13/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 255s 134ms/step - accuracy: 0.9040 - loss: 0.2325 - val_accuracy: 0.9000 - val_loss: 0.2513 - learning_rate: 5.6000e-04
Epoch 14/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.9035 - loss: 0.2334
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0003919999697245657.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 250s 131ms/step - accuracy: 0.9035 - loss: 0.2334 - val_accuracy: 0.9063 - val_loss: 0.2500 - learning_rate: 5.6000e-04
Epoch 15/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 223s 117ms/step - accuracy: 0.9088 - loss: 0.2170 - val_accuracy: 0.9093 - val_loss: 0.2390 - learning_rate: 3.9200e-04
Epoch 16/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 226s 119ms/step - accuracy: 0.9184 - loss: 0.2043 - val_accuracy: 0.9190 - val_loss: 0.2065 - learning_rate: 3.9200e-04
Epoch 17/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 485s 256ms/step - accuracy: 0.9190 - loss: 0.2015 - val_accuracy: 0.9262 - val_loss: 0.1934 - learning_rate: 3.9200e-04
Epoch 18/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 384s 202ms/step - accuracy: 0.9227 - loss: 0.1893 - val_accuracy: 0.9116 - val_loss: 0.2223 - learning_rate: 3.9200e-04
Epoch 19/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.9205 - loss: 0.1973
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.00027439997065812347.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 253s 133ms/step - accuracy: 0.9205 - loss: 0.1973 - val_accuracy: 0.9045 - val_loss: 0.2354 - learning_rate: 3.9200e-04
Epoch 20/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 287s 151ms/step - accuracy: 0.9254 - loss: 0.1830 - val_accuracy: 0.9063 - val_loss: 0.2550 - learning_rate: 2.7440e-04
Epoch 21/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.9309 - loss: 0.1747
Epoch 21: ReduceLROnPlateau reducing learning rate to 0.00019207997538615016.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 257s 135ms/step - accuracy: 0.9309 - loss: 0.1747 - val_accuracy: 0.9254 - val_loss: 0.1987 - learning_rate: 2.7440e-04
Epoch 22/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 256s 135ms/step - accuracy: 0.9345 - loss: 0.1653 - val_accuracy: 0.9254 - val_loss: 0.1967 - learning_rate: 1.9208e-04
Epoch 23/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 246s 129ms/step - accuracy: 0.9325 - loss: 0.1687 - val_accuracy: 0.9294 - val_loss: 0.1931 - learning_rate: 1.9208e-04
Epoch 24/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 232s 122ms/step - accuracy: 0.9412 - loss: 0.1577 - val_accuracy: 0.9246 - val_loss: 0.2002 - learning_rate: 1.9208e-04
Epoch 25/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 240s 126ms/step - accuracy: 0.9404 - loss: 0.1509 - val_accuracy: 0.9288 - val_loss: 0.1899 - learning_rate: 1.9208e-04
Epoch 26/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 248s 131ms/step - accuracy: 0.9428 - loss: 0.1508 - val_accuracy: 0.9291 - val_loss: 0.1891 - learning_rate: 1.9208e-04
Epoch 27/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 252s 133ms/step - accuracy: 0.9427 - loss: 0.1516 - val_accuracy: 0.9267 - val_loss: 0.1981 - learning_rate: 1.9208e-04
Epoch 28/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.9388 - loss: 0.1545
Epoch 28: ReduceLROnPlateau reducing learning rate to 0.00013445597869576886.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 219s 115ms/step - accuracy: 0.9388 - loss: 0.1545 - val_accuracy: 0.9299 - val_loss: 0.1984 - learning_rate: 1.9208e-04
Epoch 29/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 250s 131ms/step - accuracy: 0.9357 - loss: 0.1564 - val_accuracy: 0.9288 - val_loss: 0.1953 - learning_rate: 1.3446e-04
Epoch 30/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 247s 130ms/step - accuracy: 0.9461 - loss: 0.1362 - val_accuracy: 0.9336 - val_loss: 0.1849 - learning_rate: 1.3446e-04
Epoch 31/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 223s 117ms/step - accuracy: 0.9466 - loss: 0.1396 - val_accuracy: 0.9333 - val_loss: 0.1919 - learning_rate: 1.3446e-04
Epoch 32/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.9454 - loss: 0.1357
Epoch 32: ReduceLROnPlateau reducing learning rate to 0.0001.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 221s 116ms/step - accuracy: 0.9454 - loss: 0.1357 - val_accuracy: 0.9310 - val_loss: 0.1929 - learning_rate: 1.3446e-04
Epoch 33/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 220s 116ms/step - accuracy: 0.9465 - loss: 0.1364 - val_accuracy: 0.9333 - val_loss: 0.1797 - learning_rate: 1.0000e-04
Epoch 34/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 222s 117ms/step - accuracy: 0.9489 - loss: 0.1264 - val_accuracy: 0.9302 - val_loss: 0.1902 - learning_rate: 1.0000e-04
Epoch 35/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 270s 142ms/step - accuracy: 0.9519 - loss: 0.1222 - val_accuracy: 0.9349 - val_loss: 0.1867 - learning_rate: 1.0000e-04
Epoch 36/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 252s 132ms/step - accuracy: 0.9451 - loss: 0.1364 - val_accuracy: 0.9331 - val_loss: 0.1908 - learning_rate: 1.0000e-04
Epoch 37/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 255s 134ms/step - accuracy: 0.9519 - loss: 0.1227 - val_accuracy: 0.9352 - val_loss: 0.1844 - learning_rate: 1.0000e-04
Epoch 38/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 223s 117ms/step - accuracy: 0.9525 - loss: 0.1226 - val_accuracy: 0.9317 - val_loss: 0.1910 - learning_rate: 1.0000e-04
Epoch 39/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 234s 123ms/step - accuracy: 0.9525 - loss: 0.1249 - val_accuracy: 0.9341 - val_loss: 0.1934 - learning_rate: 1.0000e-04
Epoch 40/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 221s 116ms/step - accuracy: 0.9492 - loss: 0.1287 - val_accuracy: 0.9357 - val_loss: 0.1985 - learning_rate: 1.0000e-04
119/119 ━━━━━━━━━━━━━━━━━━━━ 11s 90ms/step

🔁 Fold 4/5
Epoch 1/40

c:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

1890/1890 ━━━━━━━━━━━━━━━━━━━━ 313s 157ms/step - accuracy: 0.6191 - loss: 0.6375 - val_accuracy: 0.7828 - val_loss: 0.4544 - learning_rate: 8.0000e-04
Epoch 2/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 279s 146ms/step - accuracy: 0.7662 - loss: 0.4859 - val_accuracy: 0.8283 - val_loss: 0.3794 - learning_rate: 8.0000e-04
Epoch 3/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 225s 118ms/step - accuracy: 0.7988 - loss: 0.4301 - val_accuracy: 0.8561 - val_loss: 0.3358 - learning_rate: 8.0000e-04
Epoch 4/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 210s 110ms/step - accuracy: 0.8317 - loss: 0.3836 - val_accuracy: 0.8550 - val_loss: 0.3302 - learning_rate: 8.0000e-04
Epoch 5/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 221s 116ms/step - accuracy: 0.8443 - loss: 0.3655 - val_accuracy: 0.8741 - val_loss: 0.2952 - learning_rate: 8.0000e-04
Epoch 6/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 223s 117ms/step - accuracy: 0.8560 - loss: 0.3425 - val_accuracy: 0.8548 - val_loss: 0.3425 - learning_rate: 8.0000e-04
Epoch 7/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 220s 116ms/step - accuracy: 0.8548 - loss: 0.3432 - val_accuracy: 0.8746 - val_loss: 0.2785 - learning_rate: 8.0000e-04
Epoch 8/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 217s 114ms/step - accuracy: 0.8656 - loss: 0.3190 - val_accuracy: 0.8585 - val_loss: 0.3149 - learning_rate: 8.0000e-04
Epoch 9/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 259s 136ms/step - accuracy: 0.8705 - loss: 0.3099 - val_accuracy: 0.8841 - val_loss: 0.2643 - learning_rate: 8.0000e-04
Epoch 10/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 252s 132ms/step - accuracy: 0.8725 - loss: 0.2957 - val_accuracy: 0.8717 - val_loss: 0.2884 - learning_rate: 8.0000e-04
Epoch 11/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 267s 141ms/step - accuracy: 0.8823 - loss: 0.2925 - val_accuracy: 0.8955 - val_loss: 0.2527 - learning_rate: 8.0000e-04
Epoch 12/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 267s 140ms/step - accuracy: 0.8777 - loss: 0.2845 - val_accuracy: 0.8685 - val_loss: 0.2978 - learning_rate: 8.0000e-04
Epoch 13/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 229s 121ms/step - accuracy: 0.8866 - loss: 0.2777 - val_accuracy: 0.8870 - val_loss: 0.2485 - learning_rate: 8.0000e-04
Epoch 14/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 193s 102ms/step - accuracy: 0.8891 - loss: 0.2786 - val_accuracy: 0.8910 - val_loss: 0.2484 - learning_rate: 8.0000e-04
Epoch 15/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.8816 - loss: 0.2779
Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0005599999858532101.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 161s 85ms/step - accuracy: 0.8816 - loss: 0.2779 - val_accuracy: 0.8849 - val_loss: 0.2745 - learning_rate: 8.0000e-04
Epoch 16/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 162s 85ms/step - accuracy: 0.9027 - loss: 0.2405 - val_accuracy: 0.8987 - val_loss: 0.2410 - learning_rate: 5.6000e-04
Epoch 17/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 156s 82ms/step - accuracy: 0.9019 - loss: 0.2402 - val_accuracy: 0.9138 - val_loss: 0.2037 - learning_rate: 5.6000e-04
Epoch 18/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 167s 88ms/step - accuracy: 0.9123 - loss: 0.2199 - val_accuracy: 0.9135 - val_loss: 0.1970 - learning_rate: 5.6000e-04
Epoch 19/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 152s 80ms/step - accuracy: 0.9053 - loss: 0.2297 - val_accuracy: 0.9090 - val_loss: 0.2107 - learning_rate: 5.6000e-04
Epoch 20/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.9117 - loss: 0.2227
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0003919999697245657.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 176s 93ms/step - accuracy: 0.9117 - loss: 0.2227 - val_accuracy: 0.8934 - val_loss: 0.2366 - learning_rate: 5.6000e-04
Epoch 21/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 181s 95ms/step - accuracy: 0.9107 - loss: 0.2143 - val_accuracy: 0.9180 - val_loss: 0.1909 - learning_rate: 3.9200e-04
Epoch 22/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 190s 100ms/step - accuracy: 0.9184 - loss: 0.2027 - val_accuracy: 0.9180 - val_loss: 0.1943 - learning_rate: 3.9200e-04
Epoch 23/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9247 - loss: 0.1927
Epoch 23: ReduceLROnPlateau reducing learning rate to 0.00027439997065812347.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 183s 97ms/step - accuracy: 0.9247 - loss: 0.1927 - val_accuracy: 0.9156 - val_loss: 0.2010 - learning_rate: 3.9200e-04
Epoch 24/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 184s 97ms/step - accuracy: 0.9241 - loss: 0.1880 - val_accuracy: 0.9238 - val_loss: 0.1895 - learning_rate: 2.7440e-04
Epoch 25/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 192s 101ms/step - accuracy: 0.9292 - loss: 0.1816 - val_accuracy: 0.9238 - val_loss: 0.1830 - learning_rate: 2.7440e-04
Epoch 26/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 194s 102ms/step - accuracy: 0.9273 - loss: 0.1786 - val_accuracy: 0.9143 - val_loss: 0.1972 - learning_rate: 2.7440e-04
Epoch 27/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.9310 - loss: 0.1725
Epoch 27: ReduceLROnPlateau reducing learning rate to 0.00019207997538615016.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 220s 116ms/step - accuracy: 0.9310 - loss: 0.1725 - val_accuracy: 0.9212 - val_loss: 0.1948 - learning_rate: 2.7440e-04
Epoch 28/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 230s 121ms/step - accuracy: 0.9374 - loss: 0.1598 - val_accuracy: 0.9238 - val_loss: 0.1863 - learning_rate: 1.9208e-04
Epoch 29/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 207s 109ms/step - accuracy: 0.9378 - loss: 0.1607 - val_accuracy: 0.9294 - val_loss: 0.1799 - learning_rate: 1.9208e-04
Epoch 30/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 214s 113ms/step - accuracy: 0.9384 - loss: 0.1572 - val_accuracy: 0.9307 - val_loss: 0.1799 - learning_rate: 1.9208e-04
Epoch 31/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9389 - loss: 0.1630
Epoch 31: ReduceLROnPlateau reducing learning rate to 0.00013445597869576886.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 192s 101ms/step - accuracy: 0.9389 - loss: 0.1630 - val_accuracy: 0.9291 - val_loss: 0.1908 - learning_rate: 1.9208e-04
Epoch 32/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 212s 112ms/step - accuracy: 0.9405 - loss: 0.1543 - val_accuracy: 0.9302 - val_loss: 0.1732 - learning_rate: 1.3446e-04
Epoch 33/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 188s 99ms/step - accuracy: 0.9374 - loss: 0.1545 - val_accuracy: 0.9354 - val_loss: 0.1650 - learning_rate: 1.3446e-04
Epoch 34/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 183s 97ms/step - accuracy: 0.9410 - loss: 0.1513 - val_accuracy: 0.9373 - val_loss: 0.1625 - learning_rate: 1.3446e-04
Epoch 35/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 183s 97ms/step - accuracy: 0.9436 - loss: 0.1437 - val_accuracy: 0.9312 - val_loss: 0.1741 - learning_rate: 1.3446e-04
Epoch 36/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9424 - loss: 0.1458
Epoch 36: ReduceLROnPlateau reducing learning rate to 0.0001.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 201s 106ms/step - accuracy: 0.9424 - loss: 0.1458 - val_accuracy: 0.9251 - val_loss: 0.1883 - learning_rate: 1.3446e-04
Epoch 37/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 188s 99ms/step - accuracy: 0.9430 - loss: 0.1425 - val_accuracy: 0.9331 - val_loss: 0.1693 - learning_rate: 1.0000e-04
Epoch 38/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 190s 100ms/step - accuracy: 0.9466 - loss: 0.1373 - val_accuracy: 0.9310 - val_loss: 0.1657 - learning_rate: 1.0000e-04
Epoch 39/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 191s 101ms/step - accuracy: 0.9430 - loss: 0.1464 - val_accuracy: 0.9341 - val_loss: 0.1649 - learning_rate: 1.0000e-04
Epoch 40/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 207s 109ms/step - accuracy: 0.9454 - loss: 0.1399 - val_accuracy: 0.9339 - val_loss: 0.1766 - learning_rate: 1.0000e-04
119/119 ━━━━━━━━━━━━━━━━━━━━ 14s 117ms/step

🔁 Fold 5/5
Epoch 1/40

c:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

1890/1890 ━━━━━━━━━━━━━━━━━━━━ 354s 185ms/step - accuracy: 0.6011 - loss: 0.6497 - val_accuracy: 0.7426 - val_loss: 0.5129 - learning_rate: 8.0000e-04
Epoch 2/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 275s 145ms/step - accuracy: 0.7561 - loss: 0.4997 - val_accuracy: 0.8024 - val_loss: 0.4349 - learning_rate: 8.0000e-04
Epoch 3/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 235s 124ms/step - accuracy: 0.8098 - loss: 0.4184 - val_accuracy: 0.8254 - val_loss: 0.3926 - learning_rate: 8.0000e-04
Epoch 4/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 215s 113ms/step - accuracy: 0.8258 - loss: 0.3904 - val_accuracy: 0.8566 - val_loss: 0.3319 - learning_rate: 8.0000e-04
Epoch 5/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 219s 116ms/step - accuracy: 0.8392 - loss: 0.3691 - val_accuracy: 0.8553 - val_loss: 0.3357 - learning_rate: 8.0000e-04
Epoch 6/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 215s 114ms/step - accuracy: 0.8483 - loss: 0.3453 - val_accuracy: 0.8653 - val_loss: 0.3074 - learning_rate: 8.0000e-04
Epoch 7/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 209s 110ms/step - accuracy: 0.8551 - loss: 0.3380 - val_accuracy: 0.8714 - val_loss: 0.2930 - learning_rate: 8.0000e-04
Epoch 8/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 208s 110ms/step - accuracy: 0.8679 - loss: 0.3184 - val_accuracy: 0.8690 - val_loss: 0.3064 - learning_rate: 8.0000e-04
Epoch 9/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.8736 - loss: 0.3026
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005599999858532101.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 221s 117ms/step - accuracy: 0.8736 - loss: 0.3026 - val_accuracy: 0.8683 - val_loss: 0.3014 - learning_rate: 8.0000e-04
Epoch 10/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 197s 104ms/step - accuracy: 0.8851 - loss: 0.2731 - val_accuracy: 0.8778 - val_loss: 0.2899 - learning_rate: 5.6000e-04
Epoch 11/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 220s 116ms/step - accuracy: 0.8933 - loss: 0.2602 - val_accuracy: 0.8783 - val_loss: 0.2771 - learning_rate: 5.6000e-04
Epoch 12/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 443s 234ms/step - accuracy: 0.8969 - loss: 0.2567 - val_accuracy: 0.8905 - val_loss: 0.2514 - learning_rate: 5.6000e-04
Epoch 13/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 363s 191ms/step - accuracy: 0.8998 - loss: 0.2523 - val_accuracy: 0.8963 - val_loss: 0.2424 - learning_rate: 5.6000e-04
Epoch 14/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 227s 120ms/step - accuracy: 0.8950 - loss: 0.2526 - val_accuracy: 0.9005 - val_loss: 0.2348 - learning_rate: 5.6000e-04
Epoch 15/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 292s 154ms/step - accuracy: 0.8990 - loss: 0.2432 - val_accuracy: 0.8992 - val_loss: 0.2462 - learning_rate: 5.6000e-04
Epoch 16/40
1889/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.9022 - loss: 0.2424
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0003919999697245657.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 241s 127ms/step - accuracy: 0.9022 - loss: 0.2424 - val_accuracy: 0.9071 - val_loss: 0.2360 - learning_rate: 5.6000e-04
Epoch 17/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 211s 111ms/step - accuracy: 0.9120 - loss: 0.2121 - val_accuracy: 0.9016 - val_loss: 0.2280 - learning_rate: 3.9200e-04
Epoch 18/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 200s 106ms/step - accuracy: 0.9115 - loss: 0.2180 - val_accuracy: 0.9077 - val_loss: 0.2290 - learning_rate: 3.9200e-04
Epoch 19/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.9180 - loss: 0.2121
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.00027439997065812347.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 214s 113ms/step - accuracy: 0.9180 - loss: 0.2121 - val_accuracy: 0.8899 - val_loss: 0.2667 - learning_rate: 3.9200e-04
Epoch 20/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 213s 112ms/step - accuracy: 0.9196 - loss: 0.2036 - val_accuracy: 0.9127 - val_loss: 0.2179 - learning_rate: 2.7440e-04
Epoch 21/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 266s 140ms/step - accuracy: 0.9164 - loss: 0.2056 - val_accuracy: 0.9140 - val_loss: 0.2200 - learning_rate: 2.7440e-04
Epoch 22/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.9239 - loss: 0.1957
Epoch 22: ReduceLROnPlateau reducing learning rate to 0.00019207997538615016.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 320s 139ms/step - accuracy: 0.9239 - loss: 0.1957 - val_accuracy: 0.9127 - val_loss: 0.2235 - learning_rate: 2.7440e-04
Epoch 23/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 258s 136ms/step - accuracy: 0.9223 - loss: 0.1898 - val_accuracy: 0.9106 - val_loss: 0.2308 - learning_rate: 1.9208e-04
Epoch 24/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.9266 - loss: 0.1829
Epoch 24: ReduceLROnPlateau reducing learning rate to 0.00013445597869576886.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 258s 136ms/step - accuracy: 0.9266 - loss: 0.1829 - val_accuracy: 0.9103 - val_loss: 0.2269 - learning_rate: 1.9208e-04
Epoch 25/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 297s 157ms/step - accuracy: 0.9343 - loss: 0.1689 - val_accuracy: 0.9161 - val_loss: 0.2080 - learning_rate: 1.3446e-04
Epoch 26/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 283s 149ms/step - accuracy: 0.9373 - loss: 0.1629 - val_accuracy: 0.9169 - val_loss: 0.2148 - learning_rate: 1.3446e-04
Epoch 27/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.9390 - loss: 0.1625
Epoch 27: ReduceLROnPlateau reducing learning rate to 0.0001.
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 287s 151ms/step - accuracy: 0.9390 - loss: 0.1625 - val_accuracy: 0.9140 - val_loss: 0.2201 - learning_rate: 1.3446e-04
Epoch 28/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 280s 147ms/step - accuracy: 0.9342 - loss: 0.1676 - val_accuracy: 0.9177 - val_loss: 0.2121 - learning_rate: 1.0000e-04
Epoch 29/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 313s 165ms/step - accuracy: 0.9347 - loss: 0.1705 - val_accuracy: 0.9177 - val_loss: 0.2108 - learning_rate: 1.0000e-04
Epoch 30/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 338s 178ms/step - accuracy: 0.9418 - loss: 0.1536 - val_accuracy: 0.9201 - val_loss: 0.2089 - learning_rate: 1.0000e-04
Epoch 31/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 332s 175ms/step - accuracy: 0.9367 - loss: 0.1644 - val_accuracy: 0.9204 - val_loss: 0.2193 - learning_rate: 1.0000e-04
Epoch 32/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 326s 172ms/step - accuracy: 0.9417 - loss: 0.1526 - val_accuracy: 0.9198 - val_loss: 0.2134 - learning_rate: 1.0000e-04
Epoch 33/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 384s 173ms/step - accuracy: 0.9384 - loss: 0.1531 - val_accuracy: 0.9212 - val_loss: 0.2164 - learning_rate: 1.0000e-04
Epoch 34/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 344s 181ms/step - accuracy: 0.9380 - loss: 0.1606 - val_accuracy: 0.9235 - val_loss: 0.2075 - learning_rate: 1.0000e-04
Epoch 35/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 276s 145ms/step - accuracy: 0.9345 - loss: 0.1644 - val_accuracy: 0.9217 - val_loss: 0.2148 - learning_rate: 1.0000e-04
Epoch 36/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 332s 175ms/step - accuracy: 0.9409 - loss: 0.1498 - val_accuracy: 0.9095 - val_loss: 0.2420 - learning_rate: 1.0000e-04
Epoch 37/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 288s 151ms/step - accuracy: 0.9413 - loss: 0.1488 - val_accuracy: 0.9233 - val_loss: 0.2083 - learning_rate: 1.0000e-04
Epoch 38/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 325s 171ms/step - accuracy: 0.9408 - loss: 0.1557 - val_accuracy: 0.9225 - val_loss: 0.2109 - learning_rate: 1.0000e-04
Epoch 39/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 347s 183ms/step - accuracy: 0.9447 - loss: 0.1446 - val_accuracy: 0.9201 - val_loss: 0.2138 - learning_rate: 1.0000e-04
Epoch 40/40
1890/1890 ━━━━━━━━━━━━━━━━━━━━ 360s 190ms/step - accuracy: 0.9426 - loss: 0.1499 - val_accuracy: 0.9241 - val_loss: 0.2059 - learning_rate: 1.0000e-04
119/119 ━━━━━━━━━━━━━━━━━━━━ 17s 139ms/step
✅Entrenamiento terminado [06-04-25_15-25-10]

#### Guardar modelo y resultados

In [53]:
# Crear ruta para guardar
save_path = f"./save/{nombre_modelo}/{timestamp}"
os.makedirs(save_path, exist_ok=True)
print(f"📁 Guardando resultados en {save_path}")

# Guardar modelo
model_fold.save(os.path.join(save_path, f'{nombre_modelo}_modelo.keras'))
model_fold.save(os.path.join(save_path, f"{nombre_modelo}_modelo.h5"))
model_fold.save_weights(os.path.join(save_path, f'{nombre_modelo}_pesos.weights.h5'))

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

📁 Guardando resultados en ./save/CNN_kFold/06-04-25_15-25-10

In [60]:
!pip install numpy==1.23.5

Collecting numpy==1.23.5

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
        File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 137, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 70, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\cosme\AppData\Local\Temp\pip-build-env-yiwgduqv\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\cosme\AppData\Local\Temp\pip-build-env-yiwgduqv\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\cosme\AppData\Local\Temp\pip-build-env-yiwgduqv\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

  Using cached numpy-1.23.5.tar.gz (10.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

In [59]:
# Instala tensorflowjs si no lo tienes
# !pip install tensorflowjs

import subprocess
# Crea carpeta de salida por si no existe
output_dir = f"{save_path}/modelo_tfjs"
os.makedirs(output_dir, exist_ok=True)
modelo_h5 = os.path.join(save_path, f"{nombre_modelo}_modelo.h5")

# Convierte el modelo a formato TensorFlow.js
result = subprocess.run([
    "tensorflowjs_converter",
    "--input_format=keras",
    modelo_h5,
    output_dir
], capture_output=True, text=True)

# Mostrar la salida y errores
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)
print("Código de salida:", result.returncode)

STDOUT:

STDERR:
2025-04-06 19:10:20.266531: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-06 19:10:23.099453: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflowjs\read_weights.py:28: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.uint8, np.uint16, np.object, np.bool]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Scripts\tensorflowjs_converter.exe\__main__.py", line 4, in <module>
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflowjs\__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflowjs\converters\__init__.py", line 21, in <module>
    from tensorflowjs.converters.converter import convert
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflowjs\converters\converter.py", line 35, in <module>
    from tensorflowjs.converters import keras_h5_conversion as conversion
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflowjs\converters\keras_h5_conversion.py", line 33, in <module>
    from tensorflowjs import write_weights  # pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflowjs\write_weights.py", line 25, in <module>
    from tensorflowjs import read_weights
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflowjs\read_weights.py", line 28, in <module>
    np.uint8, np.uint16, np.object, np.bool]
                         ^^^^^^^^^
  File "C:\Users\cosme\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?

Código de salida: 1

## 4. Promedio de métricas por fold

In [61]:
df_kfold = pd.DataFrame([
    {
        "Fold": r['fold'],
        "Accuracy": round(max(r['history']['accuracy'])*100, 2),
        "Loss": round(max(r['history']['loss'])*100, 2),
        "Val_Accuracy": round(r['val_acc']*100, 2),
        "Val_Loss": round(r['val_loss']*100, 2),
        "Precision": round(r['precision']*100, 2),
        "Recall": round(r['recall']*100, 2),
        "F1-Score": round(r['f1']*100, 2)
    } for r in fold_results
])

df_kfold_mean = df_kfold.mean(numeric_only=True).round(2)
df_kfold_std = df_kfold.std(numeric_only=True).round(2)

df_kfold_val_summary = pd.DataFrame({
    "Métrica": df_kfold.columns[1:],
    "Media (%)": df_kfold_mean[1:].values,
    "Desviación (%)": df_kfold_std[1:].values
})
display(df_kfold_val_summary)

df_hiperparametros = pd.DataFrame({
    "Hiperparámetro": ["rand", "BATCH", "IMG_SIZE", "DROPOUT", "LEARNING_RATE", "FactorLR",  "EPOCHS", "PatienceES", "F_ACT", "F_ACT_2"],
    "Valor": [rand, BATCH_SIZE, IMG_SIZE, DROPOUT, LEARNING_RATE, FactorLR, EPOCHS, PatienceES, F_ACT, F_ACT_2]
})
df_hiperparametros

        Métrica  Media (%)  Desviación (%)
0      Accuracy      94.78            0.37
1          Loss      59.31            0.61
2  Val_Accuracy      93.18            0.48
3      Val_Loss      18.35            1.58
4     Precision      93.19            0.41
5        Recall      93.16            0.64
6      F1-Score      93.18            0.49

  Hiperparámetro    Valor
0           rand     6497
1          BATCH        8
2       IMG_SIZE      128
3        DROPOUT      0.3
4  LEARNING_RATE   0.0008
5       FactorLR      0.7
6         EPOCHS       40
7     PatienceES       15
8          F_ACT     relu
9        F_ACT_2  sigmoid

## 5. Evaluación

In [43]:
loss, acc = model_fold.evaluate(X_test, y_test, verbose=1)
y_pred = (model_fold.predict(X_test) > 0.5).astype(int)

# Reporte y matriz de confusion
target_names = ['neutral', 'sexy']
report = classification_report(y_test, y_pred, target_names=target_names, output_dict=True)
conf_mat = confusion_matrix(y_test, y_pred)

# Extraer matricas de la clase 'sexy'
precision = report['sexy']['precision']
recall = report['sexy']['recall']
f1 = report['sexy']['f1-score']

df_tests_metric = pd.DataFrame({
	"Métrica": ["Accuracy", "Loss", "Precision", "Recall", "F1-Score"],
	"Valor": [f"{round(acc*100, 		2)}%",
           	  f"{round(loss*100, 		2)}%",
           	  f"{round(precision*100, 	2)}%",
           	  f"{round(recall*100, 		2)}%",
           	  f"{round(f1*100, 			2)}%"]
})
df_tests_metric

66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9372 - loss: 0.1736
66/66 ━━━━━━━━━━━━━━━━━━━━ 6s 93ms/step

     Métrica   Valor
0   Accuracy   93.1%
1       Loss  19.19%
2  Precision  93.22%
3     Recall  92.95%
4   F1-Score  93.09%

## 6. Generar informe

In [46]:
report_pdf_path = os.path.join(save_path, f'informe_fold_{nombre_modelo}.pdf')
with PdfPages(report_pdf_path) as pdf:
    verde_titulo = '#042106'  ; verde_cabecera = '#e3fde6'
    azul_titulo = '#091a5f'   ; azul_cabecera = '#e3f2fd'
    naranja_titulo = '#5f2d09'; naranja_cabecera = '#fdeee3'
    # Portada + hiperparámetros
    fig = plt.figure(figsize=(6, 3))
    ax_title = fig.add_axes([0, 0.5, 1, 0.5])
    ax_title.axis('off')
    ax_title.text(0.5, 0.7, f"Informe de Validación Cruzada - {timestamp}", fontsize=14, ha='center', va='center', color='#042106')
    
    ax_table = fig.add_axes([0.2, 0, 0.6, 0.9])
    ax_table.axis('off')
    tabla = ax_table.table(cellText=df_hiperparametros.values, colLabels=df_hiperparametros.columns,
                           cellLoc='center', loc='center')
    tabla.auto_set_font_size(False)
    tabla.set_fontsize(8)
    for i in range(len(df_hiperparametros.columns)):
        tabla[0, i].set_facecolor('#e3fde6')
    pdf.savefig(fig)
    plt.close(fig)

    # Tabla resumen promedio K-Fold
    fig = plt.figure(figsize=(6, 2.2))
    ax_title = fig.add_axes([0, 0.75, 1, 0.25])
    ax_title.axis('off')
    ax_title.text(0.5, 0.5, f"Resultados Promedio con K-Fold (k={5})", fontsize=12, ha='center', color='#091a5f')
    
    ax_table = fig.add_axes([0.15, 0, 0.7, 0.85])
    ax_table.axis('off')
    tabla = ax_table.table(cellText=df_kfold_val_summary.values, colLabels=df_kfold_val_summary.columns,
                           cellLoc='center', loc='center')
    tabla.auto_set_font_size(False)
    tabla.set_fontsize(9)
    for i in range(len(df_kfold_val_summary.columns)):
        tabla[0, i].set_facecolor('#e3f2fd')
    pdf.savefig(fig)
    plt.close(fig)

    # Gráfica de barras con métricas por fold
    fig, ax = plt.subplots(figsize=(6, 4))
    df_kfold.set_index("Fold")[["Accuracy", "Precision", "Recall", "F1-Score"]].plot(kind='bar', ax=ax)
    ax.set_title('Métricas por Fold')
    ax.set_ylabel('%')
    ax.set_xticklabels([f"Fold {i}" for i in df_kfold["Fold"]])
    ax.legend(loc='upper right')
    plt.tight_layout()
    pdf.savefig(fig)
    plt.close(fig)
    
    # ================================
    # PAGINA 6: Resultados Test
    # ================================
    fig = plt.figure(figsize=(6, 2))
    ax_title = fig.add_axes([0, 0.75, 1, 0.25])
    ax_title.axis('off')
    
    ax_title.text(0.5, 0.5, f"Resultados Test [test: {len(X_test)}]", fontsize=12, ha='center', va='center', color=naranja_titulo)
    ax_table = fig.add_axes([0.25, 0, 0.5, 0.9])
    ax_table.axis('off')
    # Tabla
    tabla = ax_table.table(cellText=df_tests_metric.values, colLabels=df_tests_metric.columns, cellLoc='center', loc='center')
    tabla.auto_set_font_size(False)
    tabla.set_fontsize(9)
    for i in range(len(df_tests_metric.columns)):
        tabla[0, i].set_facecolor(naranja_cabecera)
    pdf.savefig(fig)
    plt.close(fig)

    # ================================
    # PAGINA 7: Matriz de Confusion
    # ================================
    fig, ax = plt.subplots(figsize=(6, 5))
    sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Oranges',
                xticklabels=target_names, yticklabels=target_names, ax=ax)
    ax.set_xlabel('Predicción')
    ax.set_ylabel('Real')
    ax.set_title(f'Matriz de Confusión (test)')
    pdf.savefig(fig)
    plt.close(fig)
    
	# ================================
	# PAGINA 8: Resumen del Modelo
	# ================================
    summary_lines = []
    model_fold.summary(print_fn=lambda x: summary_lines.append(x))

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.axis('off')

    # Título
    ax.text(0.5, 1.0, "Arquitectura del Modelo", fontsize=14,
            ha='center', va='bottom', transform=ax.transAxes, color=azul_titulo)

    # Imprimir cada línea
    for i, line in enumerate(summary_lines):
        y = 0.8 - (i + 1) * (0.9 / len(summary_lines))
        ax.text(0, y, line, fontsize=8, family='monospace', transform=ax.transAxes)

    pdf.savefig(fig)
    plt.close(fig)
    
print(f"Guardado: {report_pdf_path}")

Guardado: ./save/CNN_kFold/06-04-25_15-25-10\informe_fold_CNN_kFold.pdf